[global]
save_package_metadata = true
upload_resources = true
save_internal_metadata = true
download_only_new_data = true

count_workers = 4
maxsize = 4

[section]
[section.ciudad_buenos_aires]
base_url = "https://data.buenosaires.gob.ar/"
portal_name = "buenos_aires_data"

[section.argentina]
base_url = "https://datos.gob.ar/"
portal_name = "datos_argentina"