name: main_opa_runner

on:
  # push:
  #   branches: [ master ]
  workflow_dispatch:

jobs:
  opa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install internetarchive httpx
      - name: Download script
        run: wget https://raw.githubusercontent.com/lbellomo/opa/master/main.py
      - name: Run script
        run: python main.py
        env:
          IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
          IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}
      - name: Commit changes
        if: ${{ always() }}
        run: |
          git config --global user.name 'Archive bot'
          git config --global user.email 'Archive@bot.com'
          git add -A
          git commit -m "bump portals"
          git push
