name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install internetarchive httpx
      # Runs a single command using the runners shell
      - name: Download script
        run: wget https://raw.githubusercontent.com/lbellomo/opa/master/main.py
      - name: Run script
        run: python main.py
